w_euro = 0.5;
w_CO2 = 0.5;
fuel_cost = [0.1; 0; 0.05];
maintenance_cost = [0.1; 0.3; 0.05];
build_cost = [0.1; 0.2; 0.1]; % How much to build for coal and solar
CO2_cost = [0.2; 0.05; 0.1]; % How much CO2 do they emit?
%f = sum([x(1); x(2); x(3)].*(w_euro*(maintenance_cost+fuel_cost)+w_CO2*CO2_cost));
budget = 1;
total_cost_money = 0;
total_CO2 = 0;
total_cost = 0;
for i = 2:length(test)
    dx(i,:) = test(i,:)-test(i-1,:);
    cost_to_build = build_cost.*abs(dx(i,:))';
    time = sum(cost_to_build)/budget
    time_dependent_cost = time*(fuel_cost+maintenance_cost);
    time_CO2_cost = time*CO2_cost;
    total_cost_money = total_cost_money+time_dependent_cost;
    total_CO2 = total_CO2+time_CO2_cost;
    total_cost = total_cost + w_euro*total_cost_money+w_CO2*total_CO2;
end